### ISSUE TITLE
Cannot compile on GHC 8.10

### ISSUE THREAD

**Issue by ocharles** [cdepillabout/world-peace#7]
```
Building library for world-peace-1.0.1.0..
[1 of 5] Compiling Data.WorldPeace.Internal.Prism ( src/Data/WorldPeace/Internal/Prism.hs, dist/build/Data/WorldPeace/Internal/Prism.o, dist/build/Data/WorldPeace/Internal/Prism.dyn_o )
[2 of 5] Compiling Data.WorldPeace.Internal ( src/Data/WorldPeace/Internal.hs, dist/build/Data/WorldPeace/Internal.o, dist/build/Data/WorldPeace/Internal.dyn_o )
[3 of 5] Compiling Data.WorldPeace.Product ( src/Data/WorldPeace/Product.hs, dist/build/Data/WorldPeace/Product.o, dist/build/Data/WorldPeace/Product.dyn_o )

src/Data/WorldPeace/Product.hs:56:23: error:
    Not in scope: type variable ‘u’
   |
56 | instance forall (f :: u -> *) (a :: u). ToProduct (f a) f '[a] where
   |                       ^

src/Data/WorldPeace/Product.hs:56:37: error:
    Not in scope: type variable ‘u’
   |
56 | instance forall (f :: u -> *) (a :: u). ToProduct (f a) f '[a] where
   |                                     ^

src/Data/WorldPeace/Product.hs:61:23: error:
    Not in scope: type variable ‘u’
   |
61 | instance forall (f :: u -> *) (a :: u) (b :: u). ToProduct (f a, f b) f '[a, b] where
   |                       ^

src/Data/WorldPeace/Product.hs:61:37: error:
    Not in scope: type variable ‘u’
   |
61 | instance forall (f :: u -> *) (a :: u) (b :: u). ToProduct (f a, f b) f '[a, b] where
   |                                     ^

src/Data/WorldPeace/Product.hs:61:46: error:
    Not in scope: type variable ‘u’
   |
61 | instance forall (f :: u -> *) (a :: u) (b :: u). ToProduct (f a, f b) f '[a, b] where
   |                                              ^

src/Data/WorldPeace/Product.hs:66:23: error:
    Not in scope: type variable ‘u’
   |
66 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u). ToProduct (f a, f b, f c) f '[a, b, c] where
   |                       ^

src/Data/WorldPeace/Product.hs:66:37: error:
    Not in scope: type variable ‘u’
   |
66 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u). ToProduct (f a, f b, f c) f '[a, b, c] where
   |                                     ^

src/Data/WorldPeace/Product.hs:66:46: error:
    Not in scope: type variable ‘u’
   |
66 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u). ToProduct (f a, f b, f c) f '[a, b, c] where
   |                                              ^

src/Data/WorldPeace/Product.hs:66:55: error:
    Not in scope: type variable ‘u’
   |
66 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u). ToProduct (f a, f b, f c) f '[a, b, c] where
   |                                                       ^

src/Data/WorldPeace/Product.hs:71:23: error:
    Not in scope: type variable ‘u’
   |
71 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u) (d :: u). ToProduct (f a, f b, f c, f d) f '[a, b, c, d] where
   |                       ^

src/Data/WorldPeace/Product.hs:71:37: error:
    Not in scope: type variable ‘u’
   |
71 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u) (d :: u). ToProduct (f a, f b, f c, f d) f '[a, b, c, d] where
   |                                     ^

src/Data/WorldPeace/Product.hs:71:46: error:
    Not in scope: type variable ‘u’
   |
71 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u) (d :: u). ToProduct (f a, f b, f c, f d) f '[a, b, c, d] where
   |                                              ^

src/Data/WorldPeace/Product.hs:71:55: error:
    Not in scope: type variable ‘u’
   |
71 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u) (d :: u). ToProduct (f a, f b, f c, f d) f '[a, b, c, d] where
   |                                                       ^

src/Data/WorldPeace/Product.hs:71:64: error:
    Not in scope: type variable ‘u’
   |
71 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u) (d :: u). ToProduct (f a, f b, f c, f d) f '[a, b, c, d] where
   |                                                                ^
```

**Comment by cdepillabout** [comment]
@ocharles Thanks for opening this issue.

I'd be happy to accept a PR fixing this.
