### PR TITLE
Fix build on GHC 8.10

### LINKED ISSUE #7: Cannot compile on GHC 8.10
```
Building library for world-peace-1.0.1.0..
[1 of 5] Compiling Data.WorldPeace.Internal.Prism ( src/Data/WorldPeace/Internal/Prism.hs, dist/build/Data/WorldPeace/Internal/Prism.o, dist/build/Data/WorldPeace/Internal/Prism.dyn_o )
[2 of 5] Compiling Data.WorldPeace.Internal ( src/Data/WorldPeace/Internal.hs, dist/build/Data/WorldPeace/Internal.o, dist/build/Data/WorldPeace/Internal.dyn_o )
[3 of 5] Compiling Data.WorldPeace.Product ( src/Data/WorldPeace/Product.hs, dist/build/Data/WorldPeace/Product.o, dist/build/Data/WorldPeace/Product.dyn_o )

src/Data/WorldPeace/Product.hs:56:23: error:
    Not in scope: type variable ‘u’
   |
56 | instance forall (f :: u -> *) (a :: u). ToProduct (f a) f '[a] where
   |                       ^

src/Data/WorldPeace/Product.hs:56:37: error:
    Not in scope: type variable ‘u’
   |
56 | instance forall (f :: u -> *) (a :: u). ToProduct (f a) f '[a] where
   |                                     ^

src/Data/WorldPeace/Product.hs:61:23: error:
    Not in scope: type variable ‘u’
   |
61 | instance forall (f :: u -> *) (a :: u) (b :: u). ToProduct (f a, f b) f '[a, b] where
   |                       ^

src/Data/WorldPeace/Product.hs:61:37: error:
    Not in scope: type variable ‘u’
   |
61 | instance forall (f :: u -> *) (a :: u) (b :: u). ToProduct (f a, f b) f '[a, b] where
   |                                     ^

src/Data/WorldPeace/Product.hs:61:46: error:
    Not in scope: type variable ‘u’
   |
61 | instance forall (f :: u -> *) (a :: u) (b :: u). ToProduct (f a, f b) f '[a, b] where
   |                                              ^

src/Data/WorldPeace/Product.hs:66:23: error:
    Not in scope: type variable ‘u’
   |
66 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u). ToProduct (f a, f b, f c) f '[a, b, c] where
   |                       ^

src/Data/WorldPeace/Product.hs:66:37: error:
    Not in scope: type variable ‘u’
   |
66 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u). ToProduct (f a, f b, f c) f '[a, b, c] where
   |                                     ^

src/Data/WorldPeace/Product.hs:66:46: error:
    Not in scope: type variable ‘u’
   |
66 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u). ToProduct (f a, f b, f c) f '[a, b, c] where
   |                                              ^

src/Data/WorldPeace/Product.hs:66:55: error:
    Not in scope: type variable ‘u’
   |
66 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u). ToProduct (f a, f b, f c) f '[a, b, c] where
   |                                                       ^

src/Data/WorldPeace/Product.hs:71:23: error:
    Not in scope: type variable ‘u’
   |
71 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u) (d :: u). ToProduct (f a, f b, f c, f d) f '[a, b, c, d] where
   |                       ^

src/Data/WorldPeace/Product.hs:71:37: error:
    Not in scope: type variable ‘u’
   |
71 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u) (d :: u). ToProduct (f a, f b, f c, f d) f '[a, b, c, d] where
   |                                     ^

src/Data/WorldPeace/Product.hs:71:46: error:
    Not in scope: type variable ‘u’
   |
71 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u) (d :: u). ToProduct (f a, f b, f c, f d) f '[a, b, c, d] where
   |                                              ^

src/Data/WorldPeace/Product.hs:71:55: error:
    Not in scope: type variable ‘u’
   |
71 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u) (d :: u). ToProduct (f a, f b, f c, f d) f '[a, b, c, d] where
   |                                                       ^

src/Data/WorldPeace/Product.hs:71:64: error:
    Not in scope: type variable ‘u’
   |
71 | instance forall (f :: u -> *) (a :: u) (b :: u) (c :: u) (d :: u). ToProduct (f a, f b, f c, f d) f '[a, b, c, d] where
   |                                                                ^
```

### PR DESCRIPTION
**Pull request by ocharles**
I believe these changes are also compatible with older GHCs.

Fixes #7

### CODE REVIEW

**Comment by cdepillabout** [comment]
As far as I can tell, this no longer builds on GHC-8.2 or older:

https://travis-ci.org/github/cdepillabout/world-peace/builds/699619671

I'll just disable those builds on CI, and if someone wants support for older GHCs, I'd accept a PR getting that working.

**Comment by cdepillabout** [comment]
@ocharles Are you guys using world-peace?  I depend on it in [servant-checked-exceptions](https://hackage.haskell.org/package/servant-checked-exceptions), but I wasn't aware of anyone directly using it.

**Comment by ocharles** [comment]
@cdepillabout yea, we also use that library (GHC 8.8 and above)

**Comment by cdepillabout** [comment]
@ocharles Oh, nice.

Well if there are any features you guys need, please feel free to open up issues or PRs.

I've basically added everything I needed for `servant-checked-exceptions`, but I'm not actively working on adding stuff to this library.

Also, if `world-peace` ever becomes a bottleneck for you, you may be interested in switching to a library that has had more optimizations done.

**Comment by ocharles** [comment]
Will do, thanks!
